inherit_from: rubocop-todo.yml

AlignParameters:
  Enabled: false
  
AndOr:
  Enabled: false

CyclomaticComplexity:
  Max: 18

Documentation:
  Enabled: false
  
DoubleNegation:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false
    
FormatString:
  EnforcedStyle: percent

LineLength:
  Max: 120
  Exclude:
    - lib/ecdsa/group/*.rb
    - spec/nist_example_spec.rb

