inherit_from: rubocop-todo.yml

AlignParameters:
  Enabled: false
  
AndOr:
  Enabled: false

CyclomaticComplexity:
  Max: 20

Documentation:
  Enabled: false
  
DoubleNegation:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false
    
FormatString:
  EnforcedStyle: percent

LineLength:
  Max: 120
  Exclude:
    - lib/ecdsa/group/*.rb
    - spec/nist_example_spec.rb

MethodLength:
  Max: 20
  
# Buggy cop: it was auto-correcting files that were excluded when I ran rubcop -a
NumericLiterals:
  Enabled: false
  Exclude:
    - lib/ecdsa/group/nist*.rb